// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCode(arg1) {
  return window['go']['main']['App']['ApplyCode'](arg1);
}

export function CheckDonation() {
  return window['go']['main']['App']['CheckDonation']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetMonetizationConfig() {
  return window['go']['main']['App']['GetMonetizationConfig']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ProcessDroppedPaths(arg1, arg2) {
  return window['go']['main']['App']['ProcessDroppedPaths'](arg1, arg2);
}

export function ProcessFiles(arg1, arg2) {
  return window['go']['main']['App']['ProcessFiles'](arg1, arg2);
}

export function ProcessFolder(arg1, arg2) {
  return window['go']['main']['App']['ProcessFolder'](arg1, arg2);
}

export function SelectDestFolder() {
  return window['go']['main']['App']['SelectDestFolder']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
