// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyCode(arg1:string):Promise<boolean>;

export function CheckDonation():Promise<boolean>;

export function GetLicenseInfo():Promise<main.LicenseInfo>;

export function GetMonetizationConfig():Promise<main.MonetizationConfig>;

export function IsUnlocked():Promise<boolean>;

export function ProcessDroppedPaths(arg1:Array<string>,arg2:string):Promise<main.DropResult>;

export function ProcessFiles(arg1:Array<string>,arg2:string):Promise<number>;

export function ProcessFolder(arg1:string,arg2:string):Promise<number>;

export function SelectDestFolder():Promise<string>;

export function SelectFiles():Promise<main.FileSelectionResult>;

export function SelectFolder():Promise<main.FolderSelectionResult>;

export function SetLanguage(arg1:string):Promise<void>;
